language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '10'
  - '8'
  - '6'
before_script:
  - npm prune
script:
  - npm run lint
  - npm test
after_success:
  - npm run semantic-release
branches:
  only:
    - master
